workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - build
  - package

include:
  - local: ".gitlab/ci/templates/rust-rpm.yaml"
  - local: ".gitlab/ci/el9-build.yaml"
  - local: ".gitlab/ci/fedora42-build.yaml"
