[package]
name = "git-helper"
version = "1.5.0"
authors = ["nbrandolino nickbrandolino134@gmail.com"]
edition = "2021"

[profile.release]
strip = true

[dependencies]
clap = "4.5"
dirs-next = "2.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
